### ISSUE TITLE
Recent change to antq script removed useful default behavior

### ISSUE THREAD

**Issue by jdjohnston** [borkdude/tools#10]
Currently, running `antq` without any arguments is equivalent to `antq --help`, but running `clojure -X antq.tool/outdated` without any arguments has the useful behavior of reporting any outdated dependencies. Sometimes it's useful to simply see if there are any outdated dependencies without actually making any changes to the `deps.edn`, `project.clj`, or such.

Before the most recent change, running `antq.tool/outdated` without arguments _was_ the default behavior when runing the `antq` script without arguments.

Wouldn't most users be able to guess `--help` if needed. A help option is very common these days.

This is unrelated to the other part of the change to `antq.clj`, which was adding the dependency on `org.slf4j/slf4j-nop`. That seems good. I would simply prefer the old default behavior when the script is ran without arguments. Of course, it's your code :)

**Comment by borkdude** [comment]
Feel free to provide a PR

https://www.michielborkent.nl
https://www.eetvoorjeleven.nu

**Comment by jdjohnston** [comment]
@borkdude WIP. Repo forked, but I tend to be a bit slow & have limited Internet access.

**Comment by borkdude** [comment]
No worries, let me know if you need any help with anything

**Comment by jdjohnston** [comment]
PR accepted, so closing this Issue
