### ISSUE TITLE
Enhance antq.clj by adding a dependency to SLF4J

### ISSUE THREAD

**Issue by jdjohnston** [borkdude/tools#8]
As described in [Avoid SLF4J warnings](https://github.com/liquidz/antq/blob/main/doc/avoid-slf4j-warnings.adoc).

I tried this on a local copy installed with `bbin` by adding it to the definition of `deps` (line 9 of `antq.clj`). Worked as expected in simple testing.

Thanks for making `antq` available as a `bbin` script!

**Comment by borkdude** [comment]
Done!
